### ISSUE TITLE
Status of this library/gem

### ISSUE THREAD

**Issue by skddc** [triAGENS/guacamole#121]
Hi,

I was wondering what the status of this library is, given the fact that the last commit is almost one year old, and there doesn't seem to be any activity, with native AQL Ruby support still missing.

Is this good to use in an actual project or is it abandonded or deprecrated?

**Comment by moonglum** [comment]
I'm not working for ArangoDB since April 2015. I'm not working on Guacamole, Ashikawa::Core or the AQL gem Brazil since summer of 2014 and have no plans to do so. I'm more than happy to pass the maintainership on to someone else. As the graph API changed quite significantly since then this gem is no longer supporting the current version of ArangoDB.

**Comment by skddc** [comment]
Dang, ok. Thanks for the update!

Maybe put that information in the README, too? It looks like it's good to use on first sight and the ArangoDB docs have a tutorial for Guacamole that doesn't say anything about incompatibility or deprecation.

**Comment by moonglum** [comment]
Done! Thanks for the feedback!
